name: CI Pipeline

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Generate TypeDoc
        run: npm run docs

      - name: Configure Git for deploy
        run: |
          git config --global user.name "Adrián Pérez Poleo"
          git config --global user.email "alu0101635224@ull.edu.es"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git        
        
      - name: Deploy to GitHub Pages
        run: npm run deploy