name: CI Pipeline

on:
  push:
    branches:
      - main  

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build:all

      - name: Configure Git for deploy
        run: |
          git config --global user.name "Adrián Pérez Poleo"
          git config --global user.email "alu0101635224@ull.edu.es"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git        
        
      - name: Deploy to GitHub Pages
        run: npm run deploy